FROM node:20-alpine

WORKDIR /app

# Copia apenas os arquivos de dependências primeiro (otimiza o cache do Docker)
COPY package*.json ./
RUN npm install

COPY . .

# O comando para iniciar o servidor de desenvolvimento (assumindo Vite)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
